image:
  file: .docker/gitpod/mathlib/Dockerfile

vscode:
  extensions:
    - jroesch.lean

tasks:
  - init: leanpkg config && leanproject get-cache --fallback=download-all
    command: . /home/gitpod/.profile
