pull_request_rules:
  - name: automatic merge on CI success and review - push
    conditions:
      - status-success=Build mathlib
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=@leanprover-community/mathlib-maintainers
    actions:
     delete_head_branch: {}
     merge:
        method: squash
        strict: smart
        strict_method: merge
 # In practice this turns out to be really annoying.
 # - name: remove outdated reviews
 #   conditions:
 #     - base=master
 #   actions:
 #     dismiss_reviews:
 #       approved: True
