language: generic

install:
  - curl https://leanprover.github.io/lean-nightly/build/lean-nightly-linux.tar.gz | tar xz -C ..
  - export PATH=../lean-nightly-linux/bin:$PATH

script:
  - leanpkg test
  - lean --recursive --export=mathlib.txt
  - leanchecker mathlib.txt

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
