language: c
sudo: false
go:
- 1.11.x
os:
    - linux
addons:
    packages:
        - python3.4
branches:
  except:
    - /^lean-.*$/

cache:
  directories:
    - $TRAVIS_BUILD_DIR/test/
    - $TRAVIS_BUILD_DIR/src/
    - $HOME/.elan

before_install:
  - python3.4 -m venv .venv --without-pip
  - curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - .venv/bin/python get-pip.py

install:
  - .venv/bin/python -m pip install toml
  - export LEAN_VERSION=`.venv/bin/python scripts/lean_version.py`
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  - ./purge_olean.sh
  - rm mathlib.txt || true

jobs:
  include:
    - stage: Pre-build-1
      script:
        - travis_long "timeout 2400 leanpkg test" || true

    - stage: Pre-build-2
      script:
        - travis_long "timeout 2400 leanpkg test" || true

    - stage: Test
      script:
        - leanpkg test
        - lean --recursive --export=mathlib.txt src/
        - leanchecker mathlib.txt
        - sh scripts/deploy_nightly.sh

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
