language: c

sudo: false

os:
    - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/*/

install:
  - curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
  - source ~/.elan/env

jobs:
  include:
    - stage: Pre-build
      script:
        - rm mathlib.txt || true
        - timeout 2400 leanpkg test || echo timed out
        - find . -name "*.lean" -delete

    - stage: Test
      script:
        - leanpkg test
        - lean --recursive --export=mathlib.txt
        - leanchecker mathlib.txt
        - find . -name "*.lean" -delete

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
