name: Add mathlib4 porting comments

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:  # todo: remove

jobs:
  build:
    name: Update comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install latest mathlibtools
        run: |
          pip install git+https://github.com/leanprover-community/mathlib-tools

      - name: update docstrings
        run: |
          python ./scripts/add_port_comments.py

      - name: generate message
        id: generate-message-bad
        run: |
          PR_LIST="$(git diff HEAD -U0 | grep -o -e 'https://github.com/leanprover-community/mathlib4/pull/[0-9]\+'  | awk '{print "* " $0}')"
          echo "PR_LIST=$(printf "%q" "$PR_LIST")" >> $GITHUB_OUTPUT
          echo "$PR_LIST"
          
      - uses: actions/github-script@v5
        id: generate-message
        with:
          script: |
            prs = exec.getExecOutput("bash",
              ['-c', "git diff HEAD -U0 | grep -o -e 'https://github.com/leanprover-community/mathlib4/pull/\\d+'"]);
            console.log(prs.stdout);
            console.log(prs.stderr);
            core.setOutput("PR_LIST", prs.stdout); 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          commit-message: "chore(*): add mathlibport comments"
          title: "chore(*): add mathlibport comments"
          body: |
            Regenerated from the [port status wiki page](https://github.com/leanprover-community/mathlib/wiki/mathlib4-port-status).
            Relates to the following PRs:
            ${{ steps.generate-message.outputs.PR_LIST }}

            ---
            I am a bot; please check that I have not put a comment in a bad place before running `bors merge`!
          labels: |
            easy
            awaiting-review
            mathlib4-synchronization
