name: update nolints

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch

jobs:
  build:
    name: Build, lint and update nolints
    runs-on: ubuntu-latest
    env:
      # number of commits to check for olean cache
      GIT_HISTORY_DEPTH: 20
    steps:
      - uses: actions/checkout@v3

      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install latest mathlibtools
        id: build
        run: |
          pip install git+https://github.com/leanprover-community/mathlib-tools

      - name: update docstrings
        id: build
        run: |
          ./scripts/add_port_comments.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
