name: Maintainer merge

on:
  issue_comment:
    types: [created, edited]

jobs:
  ping_zulip:
    name: Ping maintainers on Zulip
    if: (toJSON(github.event.issue.pull_request) != 'null') && (startsWith(github.event.comment.body, 'maintainer merge') || contains(toJSON(github.event.comment.body), '\r\nmaintainer merge'))
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        name: Get PR head
        id: get_pr_head
        with:
          route: GET /repos/:repository/pulls/:pull_number
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Parse steps.get_pr_head.outputs.data, since it is a string
      - id: parse_pr_head
        name: Parse PR head
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.get_pr_head.outputs.data }}
          head_user: 'head.user.login'

      - if: (steps.parse_pr_head.outputs.head_user == 'leanprover-community')
        name: Send message on Zulip
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'mathlib maintainers'
          type: 'stream'
          topic: 'maintainer merge'
          content: ${{ github.event.issue.number }}
