name: update nolints

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build, lint and update nolints
    if: github.repository == 'leanprover-community/mathlib'
    runs-on: ubuntu-latest
    env:
      # number of commits to check for olean cache
      GIT_HISTORY_DEPTH: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ env.GIT_HISTORY_DEPTH }}

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "::add-path::$HOME/.elan/bin"
          echo "::set-env name=short_lean_version::$(~/.elan/bin/lean --run scripts/lean_version.lean)"

      - name: install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: try to find olean cache
        run: ./scripts/fetch_olean_cache.sh

      - name: leanpkg build
        id: build
        run: leanpkg build -- -T100000 | python scripts/detect_errors.py

      - name: lint
        run: |
          ./scripts/mk_all.sh
          lean --run scripts/lint_mathlib.lean
          mv nolints.txt scripts/nolints.txt
          ./scripts/rm_all.sh
          git diff

      - name: configure git setup
        run: |
          git remote add origin-bot "https://leanprover-community-bot:${{ secrets.DEPLOY_GITHUB_TOKEN }}@github.com/leanprover-community/mathlib.git"
          git config user.email "leanprover.community@gmail.com"
          git config user.name "leanprover-community-bot"

          # By default, github actions overrides the credentials used to access any
          # github url so that it uses the github-actions[bot] user.  We want to access
          # github using a different username.
          git config --unset http.https://github.com/.extraheader

      - name: update nolints.txt
        run: ./scripts/update_nolints.sh
        env:
          DEPLOY_GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
